instance_type       = "t3.micro"
ami                 = "ami-02a2af70a66af6dfb"
name                = "dev-team-ec2-instance"
owners              = "thoughtworks-execution-team"
environment         = "dev"
