instance_type       = "t3.medium"
ami                 = "ami-02a2af70a66af6dfb"
name                = "prod-team-ec2-instance"
owners              = "thoughtworks-execution-team"
environment         = "prod"