version: 0.2

phases:
  build:
    commands:
      - terraform validate
      - tflint --chdir app/modules/
#      - tfsec app/modules
      - terraspace clean all -y
      - TS_VERSION_CHECK=0 ;TS_ENV=$ENVIRONMENT terraspace all $TERRASPACE_ACTION $STACK_NAME