buildspec.yamlversion: 0.2

env:

phases:
  build:
    commands:
      - terraform validate
      - tflint --chdir modules/
      - tfsec modules .
      - terraspace clean all -y
      - TS_ENV=$ENVIRONMENT terraspace all $TERRASPACE_ACTION $STACK_NAME