version: 0.2
#env:
#  variables:
#    TF_VAR_environment: $CODEBUILD_RESOLVED_ENV
phases:
  build:
    commands:
      - terraform validate
      - tflint --chdir app/modules/
      - tfsec app/modules -m HIGH
      - bundle install
      - terraspace clean all -y
      - export TS_VERSION_CHECK=0
      - TS_ENV=$ENVIRONMENT terraspace all $TERRASPACE_ACTION $STACK_NAME