version: 0.2
#env:
#  variables:
#    TF_VAR_environment: $CODEBUILD_RESOLVED_ENV
phases:
  build:
    commands:
      - terraform validate
      - tflint --chdir app/modules/
      - tfsec app/modules -m HIGH
      - bundle install
      - terraspace clean all -y
      - export TS_VERSION_CHECK=0
      - |
          if [[ $DEPLOY_ALL -eq 'yes' ]]; then
            echo "Deploying all stack"
            export STACK_TO_DEPLOY=all
          else
            export STACK_TO_DEPLOY=''
          fi
      - echo "RUNNING terraspace $TERRASPACE_ACTION on STACK $STACK_NAME on environment $ENVIRONMENT"
      - TS_ENV=$ENVIRONMENT terraspace $STACK_TO_DEPLOY $TERRASPACE_ACTION $STACK_NAME -y
  post_build:
    commands:
      - terraspace logs