FROM golang:1.21

# Change was made to debian packages to include the revision.
ARG tf_version=1.4.5-1


RUN apt-get update && apt-get install -y gnupg software-properties-common curl \
    && wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list \
    && apt-get update \
    && apt-get install terraform=${tf_version}

RUN CGO_ENABLED=0 go install github.com/open-policy-agent/conftest@latest