# Required variables:
vpc_id                                   = "string"
private_subnet_ids                       = [...] # list(string)
cluster_name                             = "string"
owners                                   = "string"
eks_managed_ng_instance_types            = [...] # list(string)
environment                              = "string"
enable_nat_gateway                       = any
private_route_table_ids                  = [...] # list(string)

# Optional variables:
# cluster_version                        = "1.28"
# cluster_endpoint_private_access        = true
# cluster_endpoint_public_access         = false
# cluster_security_group_name            = "eks-cluster-security-group"
# create_cloudwatch_log_group            = true
# cloudwatch_log_group_retention_in_days = "14"
# enable_irsa                            = false
# generate_kms                           = true
# deletion_eks_kms_key_days              = "7"
# custom_kms_key                         = ""
# kms_alias_name                         = "alias/eks-cluster-encryption-key1"
# enable_kms_key_rotation                = true
# cluster_endpoint_public_access_cidrs   = [...] # list(string)
# eks_managed_ng_ami_type                = "AL2_x86_64"
# eks_managed_ng_disk_size               = "50"
# eks_managed_ng_min_size                = "1"
# eks_managed_ng_max_size                = "10"
# eks_managed_ng_desired_size            = "1"
# eks_managed_ng_capacity_type           = "ON_DEMAND"
# manage_aws_auth_configmap              = false
# cluster_role_name                      = "dev-cluster-role"
# cluster_role_binding_name              = "dev-cluster-role-binding"
# k8s_group                              = "developers"
# iam_role                               = "dev-role"
# username                               = "developer"
# admin_iam_role                         = "admin-role"
# ebs_csi_driver                         = false
# amazon_cloudwatch_observability        = false
